### ISSUE TITLE
MPDL não instala no Windows

### ISSUE THREAD

**Issue by IbrahimCentralIT** [arnaldog12/Manual-Pratico-Deep-Learning#6]
Olá Arnaldo. Estou fazendo o curso pela Udemy e quando executo o comando abaixo dá um erro. Anexei um print que demonstra a tela do shell. 

Se alguém se deparou com esse mesmo erro e puder me ajudar a superá-lo, já agradeço.

Ibrahim 

COMANDO: conda create -n mpdl python numpy=1.24.3 pandas=2.0.1 matplotlib=3.7.1 scikit-learn=1.2.2 jupyter=1.0.0

![image](https://github.com/arnaldog12/Manual-Pratico-Deep-Learning/assets/141577615/96cc9474-2792-4e74-95e6-08424e58555c)

**Comment by arnaldog12** [comment]
oi, @IbrahimCentralIT 
você pode testar sem especificar a versão do pandas, por favor? 
Desse jeito:
```sh
conda create -n mpdl python numpy=1.24.3 pandas matplotlib=3.7.1 scikit-learn=1.2.2 jupyter=1.0.0
```

**Comment by IbrahimCentralIT** [comment]
Funcionou perfeitamente. #valeu

![image](https://github.com/arnaldog12/Manual-Pratico-Deep-Learning/assets/141577615/f3e087cb-cf98-4773-8e5d-99e348ed418b)
